services:
  moot:
    build: .
    volumes:
      - "./:/var/www/html"
    ports:
      - "8080:80"
  moot-frontend:
    image: node:lts-bookworm-slim
    working_dir: /app/assets/app
    entrypoint: ["/bin/bash","-c"]
    command: '"npm install; npm run dev"'
    volumes:
      - "./:/app"
    ports:
      - "5173:5173"
    